### ISSUE TITLE
Seven stable

### ISSUE THREAD

**Issue by akshatnayak27** [SupTechRM/SupTechRM#1]
Is this stable version of seven

**Comment by SupTechRM** [comment]
No, This isn't the stable version of Seven. We've taken a break from the development of the product. You can always check out videos and the website. Stay tuned! 

But no, this is not stable and you will face issues in getting many functions to work, so we do recommend installing/checking code later once the downloadable version releases. 

_Cheers, 
SupTechRM, 
Rishabh M_
